apiVersion: v1
kind: Deployment
metadata:
  name: nats
  namespace: winterhaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:latest
          ports:
            - containerPort: 8222
            - containerPort: 9222
          volumeMounts:
            - name: config
              mountPath: /etc/nats/nats.conf
              subPath: nats.conf
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8222
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: config
          configMap:
            name: nats-config