name: winterhaven

services:
  caddy:
    container_name: caddy
    image: winterhaven-caddy
    build: 
      context: ./Configuration/Caddy
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - "caddy_data:/data"
      - "caddy_config:/config"
      - ./Configuration/Caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost/"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    restart: unless-stopped

  nats:
    container_name: nats
    image: nats
    networks:
      - network
    expose:
      - "8222"
      - "9222"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222"]
    volumes:
      - ./Configuration/NATS/nats-${APPLICATION_ENVIRONMENT}.conf:/etc/nats/nats.conf:ro
    command: ["-c", "/etc/nats/nats.conf"]

  api:
    container_name: api
    image: winterhaven-api
    build:
      context: ./
      dockerfile: API/Dockerfile
    networks:
      - network
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/Health/Get"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    restart: unless-stopped

  gateway:
    container_name: gateway
    image: winterhaven-gateway
    build:
      context: ./
      dockerfile: Gateway/Dockerfile
    networks:
      - network
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/Health/Get"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    restart: unless-stopped

  database:
    container_name: database
    image: winterhaven-database
    build:
      context: ./Configuration/Database
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/opt/mssql
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - network
    expose:
      - "1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 5s
    restart: unless-stopped

  # server:
  #   container_name: server
  #   image: winterhaven-server
  #   build: 
  #     context: ./Server/build
  #     dockerfile: Dockerfile.Run
  #   expose:
  #     - "8080"
  #   networks:
  #     - network
  #   depends_on:
  #     web:
  #       condition: service_healthy
  #   healthcheck:
  #     test: >
  #       sh -c "echo | websocat -n --connect ws://localhost:8080 >/dev/null 2>&1"
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 5s
  #   restart: unless-stopped
    
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  caddy_data:
  caddy_config:
  data-protection-keys:
  db_data:
    driver: local
