name: winterhaven

services:
  api:
    image: winterhaven-api
    build:
      context: ./
      dockerfile: API/Dockerfile

  gateway:
    image: winterhaven-gateway
    build:
      context: ./
      dockerfile: Gateway/Dockerfile

  database:
    image: winterhaven-database
    build:
      context: ./Configuration/Database
      dockerfile: Dockerfile

  room:
    image: winterhaven-room
    build:
      context: ./Room
      dockerfile: Dockerfile
    
  builder:
    image: winterhaven-builder
    ports:
        - "22:22"
    build:
        context: ./Configuration/GMBuilder
        dockerfile: Dockerfile
    cap_add:
        - SYS_ADMIN
        - MKNOD
    security_opt:
        - seccomp:unconfined

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
