apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  labels:
    app: caddy
data:
  Caddyfile: |
    {
        # Enables structured logging to stdout
        log {
            format console
        }
    }

    :80 {
        bind 0.0.0.0

        handle_path /health {
            respond "OK"
        }

        handle {
            redir https://{host}{uri} permanent
        }
    }

    {$APP_DOMAIN} {
        bind 0.0.0.0
        tls internal

        reverse_proxy {$APP_HOST}:{$APP_PORT} {
            transport http {
                keepalive 35s
                keepalive_idle_conns 10
            }
        }
    }
