apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
