name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_server:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore src/Server.slnx

      - name: Build
        run: dotnet build src/Server.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test src/Server.slnx --configuration Release --no-build --verbosity normal

  build_room:
    name: Build Room Service
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Setup
        id: igor
        uses: bscotch/igor-setup@v1.3.0
        with:
          cache: true
          access-key: ${{secrets.ACCESS_KEY}}
          target-yyp: ${{ github.workspace }}/src/Room/Room.yyp

      - name: Build
        uses: bscotch/igor-build@v1.3.2

        with:
          yyc: false
          yyp-path: ${{ github.workspace }}/src/Room/Room.yyp
          user-dir: ${{ steps.igor.outputs.user-dir }}
