# For more information see the confluence documentation here: https://mantanimus.atlassian.net/wiki/spaces/~71202088493553e79e4ba087fc819aa26d2129/pages/66142/Deployment+and+CI+CD+Prerequisites

name: ✅ Web API
run-name: ✅ Web API

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-web-api:
    runs-on: [self-hosted]

    steps:

    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Restore Solution Dependencies
    - name: Restore Solution Dependencies
      run: msbuild src/Web/Web.sln /t:Restore
      shell: powershell

    - name: Build Solution
      run: msbuild src/Web/Web.sln /p:Configuration=Release
      shell: powershell

  build-room-server:
    runs-on: windows-2022

    steps:

    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # This step finds the YYP file in the repository and saves the path to an output
    - name: Find YYP
      id: find_yyp
      run: |
        $yyp = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter Server.yyp
        Write-Output "YYP file found at: $yyp"
        "yyp-path=$yyp" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    # Step 4: Setup the GameMaker build CLI tool Igor: https://github.com/bscotch/igor-setup
    - name: Setup Igor
      id: igor
      uses: bscotch/igor-setup@v1
      with:
        target-yyp: ${{ steps.find_yyp.outputs.yyp-path }} # Sets the runtime version based on the IDE version.
        access-key: ${{ secrets.GM_ACCESS_KEY }}

    # Step 5: # Build the Room Server https://github.com/bscotch/igor-build
    - name: Build GameMaker Project
      id: build
      uses: bscotch/igor-build@v1
      with:
        yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
        user-dir: ${{ steps.igor.outputs.user-dir }}
        yyc: false
        save-logs: true

  build-client:
    runs-on: windows-2022

    steps:

    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # This step finds the YYP file in the repository and saves the path to an output
    - name: Find YYP
      id: find_yyp
      run: |
        $yyp = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter Client.yyp
        Write-Output "YYP file found at: $yyp"
        "yyp-path=$yyp" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    # Step 4: Setup the GameMaker build CLI tool Igor: https://github.com/bscotch/igor-setup
    - name: Setup Igor
      id: igor
      uses: bscotch/igor-setup@v1
      with:
        target-yyp: ${{ steps.find_yyp.outputs.yyp-path }} # Sets the runtime version based on the IDE version.
        access-key: ${{ secrets.GM_ACCESS_KEY }}

    # Step 5: # Build the Client https://github.com/bscotch/igor-build
    - name: Build GameMaker Project
      id: build
      uses: bscotch/igor-build@v1
      with:
        yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
        user-dir: ${{ steps.igor.outputs.user-dir }}
        yyc: false
        save-logs: true
