name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    types: [ ready_for_review ]
    branches: [ "dev" ]

jobs:
  build_api:
    name: Build Web API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore src/Web/Web.sln

      - name: Build
        run: dotnet build src/Web/Web.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test src/Web/Web.sln --configuration Release --no-build --verbosity normal

