name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Extract Version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Restore
        run: dotnet restore src/Server.slnx
        env: # TODO: Remove this, hack fix for this issue: https://github.com/reactiveui/refit/issues/2114
          # Stops NuGet from going online to check revocation status
          NUGET_CERT_REVOCATION_MODE: offline

      - name: Build
        run: dotnet build src/Server.slnx --configuration Release /p:Version=${{ steps.version.outputs.VERSION }} --no-restore

      - name: Test
        run: dotnet test src/Server.slnx --configuration Release --no-build --verbosity normal

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}