name: SonarQube Analysis

on:
  push:
    branches: [ "dev" ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Sonar Begin
        run: |
          dotnet sonarscanner begin \
            /k:"mathew-odwyer_Server" \
            /o:"mathew-odwyer" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="coverage/**/coverage.opencover.xml"

      - name: Build
        run: dotnet build src/Server.slnx --no-incremental
        env: # TODO: Remove this, hack fix for this issue: https://github.com/reactiveui/refit/issues/2114
          # Stops NuGet from going online to check revocation status
          NUGET_CERT_REVOCATION_MODE: offline          

      - name: Test with Coverage
        run: |
          dotnet test src/Server.slnx \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Sonar End
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}