name: SonarQube Analysis

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Sonar Begin
        run: |
          dotnet sonarscanner begin \
            /k:"mathew-odwyer_Server" \
            /o:"mathew-odwyer" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths=coverage-api.xml
#coverage-gateway.xml

      - name: Build
        run: dotnet build src/Server.slnx --no-incremental

      - name: Find Test DLLs
        run: find . -name "*.Tests.dll" -not -path "*/obj/*"

      - name: Find Test Projects
        run: find . -name "*.Tests.csproj"

      - name: Test with Coverage
        run: |
          coverlet "src/API/Tests/bin/Winterhaven.API.Tests/x64/Debug/net9.0/Winterhaven.API.Tests.dll" \
            --target "dotnet" \
            --targetargs "test src/API/Tests/Winterhaven.API.Tests/Winterhaven.API.Tests.csproj --no-build" \
            -f=opencover -o="coverage-api.xml"

      - name: Sonar End
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        working-directory: ${{ github.workspace }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}