name: Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    types: [ ready_for_review ]
    branches: [ "dev" ]

jobs:
  build_api:
    name: Build and Test Web API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore Web API
        run: dotnet restore

      - name: Run Web API Tests
        run: dotnet test src/Web/Winterhaven.Tests/Winterhaven.Tests.csproj --configuration Release
