# For more information see the confluence documentation here: https://mantanimus.atlassian.net/wiki/spaces/~71202088493553e79e4ba087fc819aa26d2129/pages/66142/Deployment+and+CI+CD+Prerequisites

name: 🧪 Unit Tests
run-name: 🧪 Unit Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Run Web API unit tests
    - name: Run Web API Unit Tests
      run: dotnet test src/Web/Mantanimus.Tests
      shell: powershell
